#!/bin/bash

#java=$HOME/jdk1.5.0_02/bin/java

java -jar ../maude-2.7-hooks-linux/MFE-mfe-2.7/scripts/ext-tools/AProVE/aprove.jar -u cli -t $2 -p plain -m wst $1

java -jar ../maude-2.7-hooks-linux/MFE-mfe-2.7/scripts/ext-tools/AProVE/aprove.jar -u cli -t $2 -p html -m wst $1 > ../tmp/proof.html
