
(fmod MY-NAT is
 sort MY-NAT .
 op zero : -> MY-NAT .
 op succ : MY-NAT -> MY-NAT .
endfm)

(fmod FUNRULES is

 including MY-NAT .
 var $x : MY-NAT .
 var $y : MY-NAT .
 op add : MY-NAT MY-NAT -> MY-NAT .
 eq add($x, zero) = $x [label 1] .
 eq add($x, succ($y)) = succ(add($x, $y)) [label 2] .
 --- eq succ($x) = succ(succ($x)) .
 eq add($x, $y) = zero .
endfm)

--- set trace on .
--- set trace select on .
--- trace select 1 2 .

--- (reduce in FUNRULES :
---   add(succ(zero), succ(zero)) .)
