(fmod TEST1 is
  sort Nat .
  op f : Nat Nat -> Nat .
  op g : Nat -> Nat .
  var x : Nat .
  op a : -> Nat .
  op b : -> Nat .
  op c : -> Nat .
  eq f(x,x) = a .
  eq f(x, g(x)) = b .
  eq c = g(c) .
endfm)

(fmod TEST2 is
  sort Nat .
  vars x y : Nat .
  op a : -> Nat .
  op b : -> Nat .
  op f : Nat Nat Nat -> Nat .
  op g : Nat Nat -> Nat .

  eq f(a,b,x) = f(x,x,x) .
  eq g(x,y) = x .
  eq g(x,y) = y .
endfm)
